# Generated by Django 3.1.7 on 2021-03-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210330_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ManyToManyField(related_name='ingredients', to='api.Recipe'),
        ),
    ]
