# Generated by Django 3.1.7 on 2021-03-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210330_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='meat',
            field=models.BooleanField(default=False),
        ),
    ]
